;CIFRADO CESAR - DE 2 DESPLAZAMIENTOS - INPUT DE 20 CARACTERES 

;Marco Vivar 

;13/04/2021 



;ESTABLECER MODO DE VIDEO

MOV AH, 00H

MOV AL, 01H     ;RESOLUCION  40X25

INT 10H 

;LIMPIAR PANTALLA

MOV AH, 06H

MOV AL, 0H      ;LIMPIAR TODA LA PANTALLA

MOV BH, 1FH    ;ATRIBUTO

MOV CX, 00H     ;INICIALIZA RENG. COLUM.

MOV DL, 79      ;COLUM FINAL

MOV DH, 24      ;RENG FINAL

INT 10H

;COLOCA EL CURSOR PARA EL MENSAJE

MOV AH, 02H

MOV BH, 0H      ;PAGINA ACTUAL

MOV DH, 7       ;FILA DONDE SE SITUA EL CURSOR  

MOV DL, 7      ;COLUMNA DONDE SE SITUA EL CURSOR

INT 10H 

;IMPRIME UNA CADEDNA DE CARACTERES A PANTALLA

MOV AH, 09H

MOV DX, OFFSET MSG

INT 21H 

;COLOCA EL CURSOR PARA LEER UNA CADENA

MOV AH, 02H

MOV BH, 0H      ;PAGINA ACTUAL

MOV DH, 10      ;FILA DONDE SE SITUA EL CURSOR  

MOV DL, 9       ;COLUMNA DONDE SE SITUA EL CURSOR

INT 10H 

;LEE UNA CADENA DE CARACTERES DESDE EL TECLADO

MOV AH, 0AH

MOV DX, OFFSET CADENA

INT 21H 

;COLOCA EL CURSOR PARA IMPRIMIR LA CADENA CIFRADA

MOV AH, 02H

MOV BH, 0H      ;PAGINA ACTUAL

MOV DH, 13      ;FILA DONDE SE SITUA EL CURSOR  

MOV DL, 9       ;COLUMNA DONDE SE SITUA EL CURSOR

INT 10H

;CICLO PARA RECORRER LA CADENA

MOV CL, 0       ;CONTADOR

MOV SI, 2       ;SI=2

CICLO:

    CMP CL, CADENA[1]   ;HACE LA COMPARACION, ESE INDICE CONTIENE EL # DE CARACTERES INGREZADOS 
    
    JZ FIN_CICLO        ;SALE DEL CICLO CUANDO CL SEA IGUAL QUE EL # DE CARACTERERES
    
    MOV AL, CADENA[SI]  ;SE MUEVE A AL EL CARACTER HUBICADO EN EL INDICE -SI-
    
    CALL CIFRADO   ;SE INVOACA AL MODULO
    
    INC CL      ;SE INCREMENTA CL EN 1
    
    INC SI      ;SE INCREENTA -SI- EN 1
    
    JMP CICLO
    
FIN_CICLO:

;REGRESA EL CONTROL AL SISTEMA OPERATIVO

INT 20H   



;MODULO PARA CIFRAR

CIFRADO PROC NEAR 
    
    ;SE EVALUA SI EL USUARIO INGRESO 'y' o 'z' o 'Y' o 'Z'
    
    CMP AL, 79H 
    
    JE EXCEPCIONES 
    
    
    CMP AL, 7AH
    
    JE EXCEPCIONES
    
    
    CMP AL, 59H
    
    JE EXCEPCIONES
    
    
    CMP AL, 5AH
    
    JE EXCEPCIONES
    
    ;SE HACE EL DESPLAZAMIENTO PARA EL CIFRADO DE 2 DIGITOS
    
    ADD AL, 2       ;SE INCREMENTA EN 2 EL CARACTER
    
    JMP IMPRIMIR    ;SALTO INCONDICIONAL
    
    ;SE LE ASIGNA LAS DOS PRIMERAS LETRAS DEL ABECEDARIO A LAS 2 ULTIMAS RESPECTIVAMENTE
    
    EXCEPCIONES:
        
        SUB AL,26 
        
        ADD AL, 2
        
        JMP IMPRIMIR
        
    IMPRIMIR:
        
        MOV DL, AL
        
        MOV AH, 02H
        
        INT 21H
    
    RET
    
CIFRADO ENDP

MSG DB "ingresa palabra a cifrar$"

;0AH --> NUM. MAX CARACTERES POR LEER
;00H --> RESERVADO PARA QUE UNA VES LEIDA LA CADENA NOS DEJE EL NUM DE CARACTERES LEIDOS
;0BH --> SE RESERVA HASTA 11 CARACTERES (11 BYTES)
;DUP --> SE INICIALIZAN ESOS BYTES CON $  

CADENA DB 15H, 00H,16H DUP('$')


  